## Import Libraries

In [1]:
import pandas as pd
import matplotlib
import numpy as np
import scipy as sp
import IPython 
import sklearn

## Import the Data



In [2]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()
iris_dataset

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [3]:
print("Keys of iris_dataset: \n{}".format(iris_dataset.keys()))

Keys of iris_dataset: 
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [4]:
print(iris_dataset['DESCR'])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [5]:
print(iris_dataset['target_names']) # Our classes

['setosa' 'versicolor' 'virginica']


In [6]:
print(iris_dataset['feature_names']) # Our input data features

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [7]:
print(type(iris_dataset['data'])) # Our data in the form of a numpy array

<class 'numpy.ndarray'>


In [8]:
print(iris_dataset['data'].shape) #number flowers and number of charactersitics

(150, 4)


In [9]:
print(iris_dataset['data'][:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [10]:
print(type(iris_dataset['target']))

<class 'numpy.ndarray'>


In [11]:
print(iris_dataset['target'].shape)

(150,)


In [12]:
print(iris_dataset['target']) #0 means Setosa, 1 means Versicolor, 2 means Virginica

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


## Processing the Data

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris_dataset['data'], iris_dataset['target'], random_state = 0)

In [14]:
print(X_train.shape) # 74.667% of dataset

(112, 4)


In [15]:
print(X_test.shape)

(38, 4)


In [16]:
print(y_train.shape) 

(112,)


In [17]:
print(y_test.shape)

(38,)


## Build the Model - K-Nearest Neighbours

In [18]:
import tensorflow as tf
# Set random seed
tf.random.set_seed(42)

# Create a model
model_1 = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation=tf.keras.activations.relu),
    tf.keras.layers.Dense(10, activation=tf.keras.activations.relu),
    tf.keras.layers.Dense(3, activation=tf.keras.activations.softmax)
])

# Compile the model
model_1.compile(loss=tf.keras.losses.sparse_categorical_crossentropy,
               optimizer=tf.keras.optimizers.Adam(lr=0.01),
               metrics=["accuracy"])

# Fit the model
model_1.fit(X_train, y_train, epochs=200, verbose=1)
                
                

Epoch 1/200
4/4 [==============================] - 0s 869us/step - loss: 1.2937 - accuracy: 0.4375
Epoch 2/200
4/4 [==============================] - 0s 992us/step - loss: 1.0005 - accuracy: 0.3661
Epoch 3/200
4/4 [==============================] - 0s 1ms/step - loss: 0.8696 - accuracy: 0.5268
Epoch 4/200
4/4 [==============================] - 0s 6ms/step - loss: 0.7817 - accuracy: 0.5893
Epoch 5/200
4/4 [==============================] - 0s 1ms/step - loss: 0.7085 - accuracy: 0.7500
Epoch 6/200
4/4 [==============================] - 0s 991us/step - loss: 0.6285 - accuracy: 0.8036
Epoch 7/200
4/4 [==============================] - 0s 868us/step - loss: 0.5648 - accuracy: 0.9554
Epoch 8/200
4/4 [==============================] - 0s 992us/step - loss: 0.5029 - accuracy: 0.8036
Epoch 9/200
4/4 [==============================] - 0s 868us/step - loss: 0.4074 - accuracy: 0.9196
Epoch 10/200
4/4 [==============================] - 0s 1ms/step - loss: 0.3553 - accuracy: 0.9821
Epoch 11/200
4/4 

4/4 [==============================] - 0s 868us/step - loss: 0.0431 - accuracy: 0.9821
Epoch 84/200
4/4 [==============================] - 0s 1ms/step - loss: 0.0484 - accuracy: 0.9732
Epoch 85/200
4/4 [==============================] - 0s 992us/step - loss: 0.0633 - accuracy: 0.9732
Epoch 86/200
4/4 [==============================] - 0s 868us/step - loss: 0.0596 - accuracy: 0.9732
Epoch 87/200
4/4 [==============================] - 0s 992us/step - loss: 0.0653 - accuracy: 0.9643
Epoch 88/200
4/4 [==============================] - 0s 1ms/step - loss: 0.0366 - accuracy: 0.9911
Epoch 89/200
4/4 [==============================] - 0s 867us/step - loss: 0.0346 - accuracy: 0.9821
Epoch 90/200
4/4 [==============================] - 0s 1ms/step - loss: 0.0453 - accuracy: 0.9821
Epoch 91/200
4/4 [==============================] - 0s 868us/step - loss: 0.0353 - accuracy: 0.9911
Epoch 92/200
4/4 [==============================] - 0s 1ms/step - loss: 0.0399 - accuracy: 0.9732
Epoch 93/200
4/4 [===

4/4 [==============================] - 0s 992us/step - loss: 0.0752 - accuracy: 0.9732
Epoch 164/200
4/4 [==============================] - 0s 2ms/step - loss: 0.0491 - accuracy: 0.9732
Epoch 165/200
4/4 [==============================] - 0s 1ms/step - loss: 0.0284 - accuracy: 0.9821
Epoch 166/200
4/4 [==============================] - 0s 1ms/step - loss: 0.0403 - accuracy: 0.9821
Epoch 167/200
4/4 [==============================] - 0s 992us/step - loss: 0.0306 - accuracy: 0.9821
Epoch 168/200
4/4 [==============================] - 0s 992us/step - loss: 0.0400 - accuracy: 0.9821
Epoch 169/200
4/4 [==============================] - 0s 1ms/step - loss: 0.0228 - accuracy: 0.9911
Epoch 170/200
4/4 [==============================] - 0s 992us/step - loss: 0.0659 - accuracy: 0.9643
Epoch 171/200
4/4 [==============================] - 0s 1ms/step - loss: 0.0859 - accuracy: 0.9554
Epoch 172/200
4/4 [==============================] - 0s 868us/step - loss: 0.0420 - accuracy: 0.9821
Epoch 173/200


## Making Predictions

In [19]:
X_new = np.array([[5,2.9,1,0.2]])
print(X_new.shape)

(1, 4)


In [20]:
prediction = model_1.predict(X_new)
preds_float = prediction.round()
preds_int = preds_float. astype(int)
print(iris_dataset['target_names'][np.argmax(preds_int)])


setosa


## Evaluating the nodel

In [21]:
y_pred=model_1.predict(X_test)
print(y_pred)

[[1.22363343e-11 1.54158477e-06 9.99998450e-01]
 [1.76309113e-04 9.99543965e-01 2.79677188e-04]
 [9.99952078e-01 4.78767943e-05 1.55763098e-12]
 [7.06125644e-11 4.13370508e-05 9.99958634e-01]
 [9.99785960e-01 2.14023603e-04 9.51575138e-11]
 [1.07876016e-13 1.51106807e-08 1.00000000e+00]
 [9.99822199e-01 1.77829395e-04 5.72102504e-11]
 [2.06384848e-05 9.99744356e-01 2.35041996e-04]
 [1.07919896e-05 9.99529123e-01 4.60020616e-04]
 [2.07623481e-04 9.99673605e-01 1.18798082e-04]
 [1.13314593e-08 5.43578179e-04 9.99456465e-01]
 [5.20457834e-05 9.99778211e-01 1.69679653e-04]
 [4.74076442e-05 9.98482883e-01 1.46977918e-03]
 [1.28058564e-05 9.99311566e-01 6.75727380e-04]
 [3.03951856e-05 9.94308174e-01 5.66147594e-03]
 [9.99858499e-01 1.41530065e-04 3.05607067e-11]
 [3.02470580e-05 9.96774256e-01 3.19538731e-03]
 [8.93393953e-05 9.92775083e-01 7.13551277e-03]
 [9.99522924e-01 4.77056718e-04 6.42090048e-10]
 [9.99909520e-01 9.04432454e-05 8.93500291e-12]
 [5.85927706e-09 2.85466493e-04 9.997145

In [22]:
model_1.evaluate(X_test, y_test)

2/2 [==============================] - 0s 993us/step - loss: 0.1267 - accuracy: 0.9737


[0.126695916056633, 0.9736841917037964]